/**
 * Cardano DB-Sync API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TokenDetails {
  slotNo: number;
  maPolicyId: string;
  maName: string;
  fingerprint: string;
  metadata?: string;
  maPolicyScript: string;
  txHash: string;
  totalSupply: number;
}
