/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressPrivate } from './addressPrivate';
import { PolicyPrivate } from './policyPrivate';

export interface AccountPrivate { 
    key: string;
    createdAt: Date;
    policies: Array<PolicyPrivate>;
    address: AddressPrivate;
    fundingAddresses: Array<string>;
    fundingAddressesHistory: Array<string>;
    stake: number;
    lastUpdate: Date;
}