/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AccountStatementRow { 
    timestamp?: Date;
    epoch?: number;
    txHash?: string;
    withdrawn?: number;
    rewards?: number;
    out?: number;
    _in?: number;
    change?: number;
    sum?: number;
    operations?: Array<string>;
}