/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Policy } from './policy';
import { Address } from './address';
import { DropNft } from './dropNft';


export interface Drop { 
    id: number;
    policy: Policy;
    address: Address;
    name: string;
    price: number;
    maxPerTransaction: number;
    running: boolean;
    profitAddress: string;
    whitelist: Array<string>;
    dropNfts: Array<DropNft>;
    dropNftsSoldAssetNames: Array<string>;
    dropNftsAvailableAssetNames: Array<string>;
    prettyUrl: string;
    fee: number;
}

