/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TokenSubmission } from './tokenSubmission';

export interface MintOrderSubmission { 
    tokens: Array<TokenSubmission>;
    targetAddress: string;
    changeAction: MintOrderSubmission.ChangeActionEnum;
    fee: number;
}
export namespace MintOrderSubmission {
    export type ChangeActionEnum = 'RETURN' | 'KEEP' | 'TIP';
    export const ChangeActionEnum = {
        RETURN: 'RETURN' as ChangeActionEnum,
        KEEP: 'KEEP' as ChangeActionEnum,
        TIP: 'TIP' as ChangeActionEnum
    };
}