/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Token } from './token';

export interface MintOrder { 
    id?: number;
    createdAt: Date;
    account: Account;
    tokens?: Array<Token>;
    targetAddress: string;
    changeAction: MintOrder.ChangeActionEnum;
    txid?: string;
    policyScript?: string;
}
export namespace MintOrder {
    export type ChangeActionEnum = 'RETURN' | 'KEEP' | 'TIP';
    export const ChangeActionEnum = {
        RETURN: 'RETURN' as ChangeActionEnum,
        KEEP: 'KEEP' as ChangeActionEnum,
        TIP: 'TIP' as ChangeActionEnum
    };
}