/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RegistrationMetadata { 
    assetName: string;
    policyId: string;
    policy: string;
    policySkey: string;
    name: string;
    description: string;
    ticker?: string;
    url?: string;
}