/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MintOrderSubmission } from './mintOrderSubmission';

export interface Transaction {
  signedData: string;
  rawData: string;
  txId: string;
  fee: number;
  pinFee?: number;
  minOutput?: number;
  txSize: number;
  outputs: string;
  inputs: string;
  metaDataJson?: string;
  mintOrderSubmission?: MintOrderSubmission;
}
